# Generated by Django 6.0.3 on 2026-03-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardprogress',
            name='overall_payouts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
