# Generated by Django 6.0.3 on 2026-03-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0002_dashboardprogress_overall_payouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardprogress',
            name='overall_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
