# Generated by Django 6.0.3 on 2026-03-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0003_dashboardprogress_overall_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardprogress',
            name='current_challenges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
