# Generated by Django 6.0.3 on 2026-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0005_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='existing',
            field=models.BooleanField(default=False),
        ),
    ]
